title: The Geek Speaks
description: >
  The online home of Robbie Holmes known everywhere on the internet as [RobbieTheGeek](http://robbiethegeek.com), thanks for stopping by, please make yourself at home.
copyright: 2019
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: thegeekspeaksio
facebook_username: robbiethegeek
twitter_username: "robbiethegeek"
linkedin_username: "robbiethegeek"
instagram_username: robbiethegeek
pinterest_username: robbiethegeek
flickr_username:
github_username:  "robbiethegeek"
feed_icon: rss

gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
